
package ar.edu.ubp.das.action.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Feb 16 01:16:22 ART 2019
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "Ganador", namespace = "http://action.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ganador", namespace = "http://action.das.ubp.edu.ar/", propOrder = {"nro_sorteo", "id_persona", "Nombre", "Apellido", "Identificador", "Id_Consesionaria", "Nombre_Auto", "Nro_Marca", "Tipo_Modelo"})

public class Ganador {

    @XmlElement(name = "nro_sorteo")
    private java.lang.String nro_sorteo;
    @XmlElement(name = "id_persona")
    private java.lang.String id_persona;
    @XmlElement(name = "Nombre")
    private java.lang.String Nombre;
    @XmlElement(name = "Apellido")
    private java.lang.String Apellido;
    @XmlElement(name = "Identificador")
    private java.lang.String Identificador;
    @XmlElement(name = "Id_Consesionaria")
    private java.lang.String Id_Consesionaria;
    @XmlElement(name = "Nombre_Auto")
    private java.lang.String Nombre_Auto;
    @XmlElement(name = "Nro_Marca")
    private java.lang.String Nro_Marca;
    @XmlElement(name = "Tipo_Modelo")
    private java.lang.String Tipo_Modelo;

    public java.lang.String getNro_sorteo() {
        return this.nro_sorteo;
    }

    public void setNro_sorteo(java.lang.String newNro_sorteo)  {
        this.nro_sorteo = newNro_sorteo;
    }

    public java.lang.String getId_persona() {
        return this.id_persona;
    }

    public void setId_persona(java.lang.String newId_persona)  {
        this.id_persona = newId_persona;
    }

    public java.lang.String getNombre() {
        return this.Nombre;
    }

    public void setNombre(java.lang.String newNombre)  {
        this.Nombre = newNombre;
    }

    public java.lang.String getApellido() {
        return this.Apellido;
    }

    public void setApellido(java.lang.String newApellido)  {
        this.Apellido = newApellido;
    }

    public java.lang.String getIdentificador() {
        return this.Identificador;
    }

    public void setIdentificador(java.lang.String newIdentificador)  {
        this.Identificador = newIdentificador;
    }

    public java.lang.String getId_Consesionaria() {
        return this.Id_Consesionaria;
    }

    public void setId_Consesionaria(java.lang.String newId_Consesionaria)  {
        this.Id_Consesionaria = newId_Consesionaria;
    }

    public java.lang.String getNombre_Auto() {
        return this.Nombre_Auto;
    }

    public void setNombre_Auto(java.lang.String newNombre_Auto)  {
        this.Nombre_Auto = newNombre_Auto;
    }

    public java.lang.String getNro_Marca() {
        return this.Nro_Marca;
    }

    public void setNro_Marca(java.lang.String newNro_Marca)  {
        this.Nro_Marca = newNro_Marca;
    }

    public java.lang.String getTipo_Modelo() {
        return this.Tipo_Modelo;
    }

    public void setTipo_Modelo(java.lang.String newTipo_Modelo)  {
        this.Tipo_Modelo = newTipo_Modelo;
    }

}

