
package ar.edu.ubp.das.action.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Feb 16 01:16:22 ART 2019
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "Planes", namespace = "http://action.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Planes", namespace = "http://action.das.ubp.edu.ar/")

public class Planes {


}

