
package ar.edu.ubp.das.action.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Nov 10 00:43:37 ART 2018
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "Concesionaria", namespace = "http://action.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Concesionaria", namespace = "http://action.das.ubp.edu.ar/")

public class Concesionaria {
	 

}

