
package ar.edu.ubp.das.action;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-11-10T00:43:37.066-03:00
 * Generated source version: 3.1.6
 * 
 */
 
public class Concesionaria3_PortTypeServer{

    protected Concesionaria3_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.action.Concesionaria3();
        String address = "http://localhost:9090/Concesionaria3Port";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Concesionaria3_PortTypeServer();
        System.out.println("Server ready..."); 
        
        //Thread.sleep(5 * 60 * 1000); 
        //System.out.println("Server exiting");
        //System.exit(0);
    }
}
 
 