
package ar.edu.ubp.das.action;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-11-10T02:02:11.647-03:00
 * Generated source version: 3.1.6
 * 
 */
 
public class Concesionaria4_PortTypeServer{

    protected Concesionaria4_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.action.Concesionaria4();
        String address = "http://localhost:9090/Concesionaria4Port";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Concesionaria4_PortTypeServer();
        System.out.println("Server ready..."); 
        
       // Thread.sleep(5 * 60 * 1000); 
       // System.out.println("Server exiting");
       // System.exit(0);
    }
}
 
 